### ISSUE TITLE
Doesn't render properly with final ST2 release

### ISSUE THREAD

**Issue by Arise** [mitchellsimoens/Ux.layout.Accordion#1]
Hi.
It seems this layout doesn't hide properly the childs when in collapsed mode. 
The list gets hidden, but the form buttons are rendered over the accordion body.

Could this get a fix?

Thanks.

**Comment by mitchellsimoens** [comment]
If I have time to I will try but have no promises. In the meantime you could attempt to fix it and issue a pull request.
